[tool.poetry]
name = "to-do-api"
version = "0.1.0"
description = "REST API to manage a list of tasks (to-do list) per user"
authors = ["Veronica Melero <veronicamelperez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.12"
uvicorn = "^0.34.2"
sqlalchemy = "^2.0.40"
pydantic = "^2.11.4"
python-jose = {extras = ["cryptography"], version = "^3.4.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.20"
alembic = "^1.15.2"
inject = "^5.2.1"
pydantic-settings = "^2.9.1"
email-validator = "^2.2.0"
aiosqlite = "^0.21.0"
faker = "^37.1.0"
pytest = "^8.3.5"
asyncio = "^3.4.3"
pytest-asyncio = "^0.26.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
black = "^25.1.0"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
